steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'duyroka/hello-world:$TAG_NAME', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'duyroka/hello-world:$TAG_NAME']
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=gs://hellotestworld/deployment.yaml
  - --image=duyroka/hello-world:$TAG_NAME
  - --location=us-east1-b
  - --cluster=my-cluster
